---
title: "P8105 Homework 1"
author: "Connie Zhang"
date: "09/20/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r problem1 chunk1} 
library (tidyverse)
##creating a data frame#

hw_df = tibble(
norm_samp = rnorm(8),
norm_samp_logic = norm_samp >0,
vec_char = c("a", "b", "c", "d","e","f","g", "h"),
vec_factor = factor(c("blue", "blue","blue", "yellow", "yellow", "red","red", "red"))
)

##taking mean of each variable in dataframe#
mean(pull(hw_df, norm_samp))
mean(pull(hw_df, norm_samp_logic))
mean(pull(hw_df, vec_char))
mean(pull(hw_df, vec_factor))

##could not take the mean for vec_char and vec_factor, only for norm_samp and norm_samp_logic#
```

```{r problem1 chunk2}
eval = FALSE

as.numeric(pull(hw_df, norm_samp_logic))
as.numeric(pull(hw_df, vec_char))
as.numeric(pull(hw_df, vec_factor))

##logical and factor variables were converted into numeric successfully. character cannot be converted into numeric, therefore unable to take the mean. logical variable converted (true" to 1, "false" to 0). different factor levels were converted to numbers and the mean was able to be taken (blue became 1, yellow became 3, red became 2)
```

```{r problem1 chunk3}
eval = TRUE

##convert the logical vector to numeric, and multiply the random sample by the result, converting the logical vector to a factor, and multiply the random sample by the result, and convert the logical vector to a factor and then convert the result to numeric, and multiply the random sample by the result ##

as.numeric(pull(hw_df, norm_samp_logic))*(pull(hw_df, norm_samp))
as.factor(pull(hw_df, norm_samp_logic))*(pull(hw_df, norm_samp))
as.numeric(as.factor(pull(hw_df, norm_samp_logic)))*(pull(hw_df, norm_samp))
```

```{r problem 2}
##creating a second data frame named (df2)# 

set.seed(1234)

plot_df2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  vec_logic2 = x + y > 1,
  vec_numeric2 = as.numeric(vec_logic2),
  vec_factor2 = as.factor(vec_logic2)
)
```
* the size of the dataset is `r nrow(plot_df2)` rows and `r ncol(plot_df2)` columns.
* the mean of the sample is `r mean(pull(plot_df2, x))`, the median of the sample is `r median(pull(plot_df2, x))`, the standard deviation is `r sd(pull(plot_df2, x))`
* the proportion of cases for which x + y > 1 is `r mean(pull(plot_df2, vec_logic2))`

```{r problem2 scatterplot}
##create a scatterplot of y vs. x, color points using logic, numeric, and factor variables#

ggplot(plot_df2, aes(y = y, x = x, color = vec_logic2)) + geom_point()
ggplot(plot_df2, aes(y = y, x = x, color = vec_numeric2)) + geom_point()
ggplot(plot_df2, aes(y = y, x = x, color = vec_factor2)) + geom_point()
```
